n = input('Digite algo:')
print(type(n))
print('É alfanumerico?', n.isalnum())
print('É alfabetico?', n.isalpha())
print('É um número?', n.isnumeric())
print('É decimal?', n.isdecimal())
print('Só tem espaços?', n.isspace())
print('Está só em maiúsculas?', n.isupper())
print('Está só em minúsculas?', n.islower())
print('Está capitalizaa?', n.istitle())

#print(n.isidentifier())
#print(n.isprintable())
#print(n.isascii())
#print(n.isdigit())